### ISSUE TITLE
Make the two service handler implementation styles (contract-first vs dynamic TypeScript handlers) more explicit and upfront

### ISSUE THREAD

**Issue by pcholakov** [restatedev/documentation#219]
Somewhere in our documentation hierarchy, we should have a page that talks about contract-first vs. dynamic handlers - maybe before we even introduce service types:

<img width="291" alt="image" src="https://github.com/restatedev/documentation/assets/115803/8bc58c84-5585-45da-ab19-9cbe8141831c">

**Comment by gvdongen** [comment]
I think we touch upon this here: https://docs.restate.dev/services/sdk/overview
In the info box as well as in the example with an implementation of both APIs. 
I agree that we might need to add a bit more information/context here though.

**Comment by gvdongen** [comment]
@pcholakov I missed the notification for your message, sorry for the late reply.

We use the handler code first because it's the easiest to get started with. It improves the first experience with Restate. 
Besides the tour and the quickstart, I think both versions are addressed equally in the rest of the docs? One thing that is missing is a good overview of how they differ or when to use which one. Related issue: https://github.com/restatedev/devrel/issues/8

I will close this issue as the open to do is covered by https://github.com/restatedev/devrel/issues/8 (unless you disagree?)
