### ISSUE TITLE
Should we remove references to gRPC when talking about the service contract?

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#69]
Currently we mix the names protobuf/gRPC in the context of the Restate service contract, see https://github.com/search?q=repo%3Arestatedev%2Fdocumentation%20grpc&type=code.

I think we should stick with using only Protobuf or at least specify somewhere the relation between our service contracts and gRPC services, in particular given that gRPC might be offsetting for JS users: 

* Our Restate service contracts are defined using the [Protobuf IDL](https://protobuf.dev/programming-guides/proto3/#services), and we have our custom protocol to implement the "transport", that is not based at all on gRPC and works on HTTP/1 as well.
* We support gRPC and Connect at the edge of the system (ingress), to invoke Restate services.
* Some SDKs might reuse some gRPC codegen/libraries to simplify the implementation and profit from the existing ecosystem.

**Comment by pcholakov** [comment]
Just discovered this – I am also in favor of emphasizing Protobuf as the IDL and not so much gPRC. If people are familiar with gRPC, they should spot all the similarities. Otherwise we end up saying things like "Be aware we're not _actually_ doing gRPC internally..."

I think this is relevant to #219
